# API Keys
[api_key]
security_trails = ""

# Code owner's information
[owner]
author = "Spyboy"
twitter = "https://spyboy.in/twitter"
discord = "https://spyboy.in/Discord"
website = "https://spyboy.in/"
blog = "https://spyboy.blog/"
github = "https://github.com/spyboy-productions/CloakQuest3r"

# Code version information
[version]
version_tag = "1.0.5"
